### ISSUE TITLE
Vermelden van rekeningnummer op donatie pagina('s)

### ISSUE THREAD

**Issue by MartineHooptOpBeter** [MartineHooptOpBeter/website#4]
Als mensen niet online willen doneren kunnen ze met het rekeningnummer gewoon geld overmaken.

**Comment by MarcoMiltenburg** [comment]
Zodra het rekeningnummer bekend is.

**Comment by MarcoMiltenburg** [comment]
Tekst al toegevoegd in WordPress, rekeningnummer moet nog worden aangepast.
