### ISSUE TITLE
Na donatie moet de donateur een e-mail ontvangen met bevestiging van de donatie

### ISSUE THREAD

**Issue by MartineHooptOpBeter** [MartineHooptOpBeter/website#8]
Als een donateur online heeft gedoneerd moet er een e-mail worden verstuurd waarin de donatie wordt bevestigd.

**Comment by MarcoMiltenburg** [comment]
Toegevoegd met commits 24eee21ea79fce710a7ccdd16e9c94275a7c1bcc en a98e27278f785e7905e594b07dba22b24f8ab9dc
